# Numpy 원소의 정렬

In [1]:
import numpy as np

In [2]:
# 오름차순 정렬
array = np.array([5, 10, 20, 30, 2])
array.sort()
print(array)

[ 2  5 10 20 30]


In [3]:
# 내림차순 정렬
print(array[::-1])

[30 20 10  5  2]


In [4]:
# 각 열을 기준으로 정렬
array = np.array([[5, 10, 20, 30, 2],[7, 3, 5, 62, 6]])
org_array = array.copy()
print("각 열을 기준으로 정렬 전 \n", array)

array.sort(axis=0)
print("각 열을 기준으로 정렬 후 \n", array)

# 각 행을 기준으로 정렬
print("각 행을 기준으로 정렬 전 \n", org_array)

org_array.sort(axis=1)
print("각 행을 기준으로 정렬 후 \n", org_array)

각 열을 기준으로 정렬 전 
 [[ 5 10 20 30  2]
 [ 7  3  5 62  6]]
각 열을 기준으로 정렬 후 
 [[ 5  3  5 30  2]
 [ 7 10 20 62  6]]
각 행을 기준으로 정렬 전 
 [[ 5 10 20 30  2]
 [ 7  3  5 62  6]]
각 행을 기준으로 정렬 후 
 [[ 2  5 10 20 30]
 [ 3  5  6  7 62]]


# Numpy 균일한 간격으로 데이터 생성

In [5]:
# 균일한 간격으로 데이터 생성 : linspace [시작, 끝, 시작과 끝 사이에 몇 개의 데이터를 만들거냐]
# 더미 데이터 생성하는 경우에 많이 사용됌
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


# 난수의 재연 (실행 마다 결과 동일)

In [6]:
np.random.seed(4444)
print(np.random.randint(0, 10, (2, 3)))

[[9 9 9]
 [3 5 6]]


# numpy 배열 객체 복사

In [8]:
array1 = np.arange(0, 10)
array2 = array1

array2[0] = 99

print(array2)
print(array1)
# array1과 array2는 같은 주소임 그래서 array2를 수정할 시 array1도 변경됌

[99  1  2  3  4  5  6  7  8  9]
[99  1  2  3  4  5  6  7  8  9]


In [9]:
# 위 현상을 해결하기 위해
array3 = np.arange(0, 10)
array4 = array3.copy()
array4[0]=99

print(array3)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]


# numpy 중복된 원소 제거

In [10]:
array = np.array([1, 1, 2, 2, 3, 3, 4])
print("원소 값 : ", array)
temp = np.unique(array)
print("중복 원소 처리 : ", temp)

원소 값 :  [1 1 2 2 3 3 4]
중복 원소 처리 :  [1 2 3 4]
