In [1]:
import numpy as np

In [2]:
# 예시 데이터 생성
x = np.array([1, 2, 3, 4, 5])  # 변수 x의 값
y = np.array([2, 4, 6, 8, 10])  # 변수 y의 값
z = np.array([3, 6, 9, 12, 15])  # 변수 z의 값

In [3]:
# 공분산 계산
cov_matrix = np.cov([x, y, z])
print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]]


In [5]:
# 상관 행렬 계산
cor_matrix = np.corrcoef([x, y, z])
print("Correlation Matrix:")
print(cor_matrix)

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
