In [1]:
import numpy as np

In [2]:
# 예시 데이터 생성
x1 = np.array([1, 2, 3, 4, 5])  # 변수 x1의 값
x2 = np.array([2, 4, 6, 8, 10])  # 변수 x2의 값
x3 = np.array([3, 6, 9, 12, 15])  # 변수 x3의 값

In [3]:
# 데이터 행렬 생성
data = np.vstack([x1, x2, x3]).T

In [4]:
# 상관 행렬 계산
cor_matrix = np.corrcoef(data, rowvar=False)

In [5]:
# 각 변수들 간의 상관 계수 출력
print("Correlation coefficients:")
print(cor_matrix)

Correlation coefficients:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# 다중공선성 판단
threshold = 0.7  # 상관 계수의 임계값 설정

print("Variables with high multicollinearity:")
for i in range(cor_matrix.shape[0]):
    for j in range(i+1, cor_matrix.shape[1]):
        if abs(cor_matrix[i, j]) > threshold:
            print(f"Variable{i+1} and Variable {j+1}")

Variables with high multicollinearity:
Variable1 and Variable 2
Variable1 and Variable 3
Variable2 and Variable 3
